defaults:
  - override hydra/launcher: joblib

hydra:
  sweeper:
    params:
      wind_system_capacity: range(0, 33000, step=3000)
      solar_system_capacity: range(0, 44000, step=4000)
      battery_capacity: range(0, 67500, step=7500)


wind_system_capacity: 40000
solar_system_capacity: 30000
wind_turbine_model: GE 1.5sle
battery_capacity: 60000
single_cell_capacity: 19.14

file_paths:
  power_data: ${hydra:runtime.cwd}/data/power_data_ce.csv
  wind_data: ${hydra:runtime.cwd}/data/wind_data_houston.csv
  solar_data: ${hydra:runtime.cwd}/data/29.76_-95.37_psm3-5min_5_2020.csv
  solar_config: ${hydra:runtime.cwd}/data/pvwatts_config.json
  wind_config: ${hydra:runtime.cwd}/data/windpower_config.json
  wind_turbines: ${hydra:runtime.cwd}/data/Wind_Turbines.csv
  carbon_data: ${hydra:runtime.cwd}/data/US-TEX-ERCO_2024_hourly_(houston).csv